export const styles = {
  app: {
    textAlign: 'center',
    maxWidth: '45rem',
    margin: '0 auto',
  },
  appBar: {
    position: 'fixed',
    backgroundColor: '#000',
    width: '100%',
    maxWidth: '45rem',
    height: '10vh',
    minHeight: '3rem',
    padding: '0 1rem',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    zIndex: 1000,
  },
  title: {
    textTransform: 'uppercase',
    color: '#fff',
    fontWeight: 700,
    background:
      'linear-gradient(to right, #ffc11f, #fe650d, #f33c04, #da1f05, #a10100)',
    backgroundSize: '200% auto',
    backgroundClip: 'text',
    textFillColor: 'transparent',
    webkitBackgroundClip: 'text',
    webkitTextFillColor: 'transparent',
    animation: 'textclip 2.5s linear infinite',
    '& @keyframes textclip': {
      to: {
        backgroundPosition: '200% center',
      },
    },
  },
  headerWrapper: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    cursor: 'pointer',
  },
  section: {
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'center',
    minHeight: '100vh',
    background: 'linear-gradient(to top left, #000000, #000080, #4682B4)',
  },
  main: {
    padding: '0.625rem',
    margin: '10vh 0 10vh',
    display: 'flex',
    flexDirection: 'column',
  },
  messageForm: {
    minHeight: '10vh',
    position: 'fixed',
    bottom: 0,
    backgroundColor: '#181717',
    width: '100%',
    maxWidth: '45rem',
    display: 'flex',
  },
  sendButton: {
    backgroundColor: '#282c34',
    borderRadius: 0,
    padding: '1rem 2rem',
    cursor: 'pointer',
  },
  messageWrapper: {
    maxWidth: '70%',
    display: 'flex',
    flexDirection: 'column',
  },
  sentMessage: {
    display: 'flex',
    flexDirection: 'row-reverse',
    alignItems: 'center',
    '& p': {
      color: '#fff',
      background: '#0b93f6',
      alignSelf: 'flex-end',
      width: 'fit-content',
    },
    '& span': {
      alignSelf: 'flex-end',
    },
    '&:hover': {
      cursor: 'pointer',
    },
  },
  receivedMessage: {
    display: 'flex',
    alignItems: 'center',
    '& p': {
      background: '#e5e5ea',
      color: '#000',
      width: 'fit-content',
    },
  },
  userAvatar: {
    width: '2.5rem',
    height: '2.5rem',
    borderRadius: '50%',
    margin: '0.125rem 0.375rem',
    textTransform: 'uppercase',
  },
  messageText: {
    maxWidth: '100%',
    marginBottom: '0.75rem',
    lineHeight: '1.5rem',
    padding: '0.625rem 1.25rem',
    borderRadius: '1.5rem',
    position: 'relative',
    textAlign: 'left',
    overflowWrap: 'break-word',
  },
  messageTime: {
    fontSize: '0.75rem',
    color: '#fafafa!important',
    backgroundColor: 'transparent!important',
    width: 'fit-content',
    padding: '0.125rem 0.25rem',
    margin: 0,
  },
  deleteButton: {
    width: 46,
    height: 46,
    color: 'red',
  },
  animatedLink: {
    cursor: 'pointer',
  },
};
